version: '3.8'

services:
  go-api:
    build: ./go-api
    ports:
      - "8081:8080"
    container_name: go-api
    restart: unless-stopped
    environment:
      - GIN_MODE=release

  python-api:
    build: ./python-api
    ports:
      - "8082:8080"
    container_name: python-api
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

  node-api:
    build: ./node-api
    ports:
      - "8083:8080"
    container_name: node-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  dotnet-api:
    build: ./dotnet-api
    ports:
      - "8084:8080"
    container_name: dotnet-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

networks:
  default:
    name: api-benchmark-network 